#!/usr/bin/env python
#################################################################################
# Copyright 2018 ROBOTIS CO., LTD.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#################################################################################

# Authors: Gilbert #
# Authors: Andreas Bugge & Mathies Schou #

# Importing the necessary libraries
import rospy
import math
from sensor_msgs.msg import LaserScan
from geometry_msgs.msg import Twist
import smbus2
import time

# Global Variables
LINEAR_VEL = 0.22
STOP_DISTANCE = 0.2
LIDAR_ERROR = 0.05
SAFE_STOP_DISTANCE = STOP_DISTANCE + LIDAR_ERROR
TURNING_DISTANCE = 0.4
COLLISION_DISTANCE = 0.2
BACK_VAL = 0.15

class RGB():
    def __init__(self):
        self.bus = smbus2.SMBus(1)
        time.sleep(0.5)
        self.bus.write_byte_data(0x44, 0x01, 0x05)
        
    def Color(self):
        Red = self.bus.read_word_data(0x44, 0x0B)
        Green = self.bus.read_word_data(0x44, 0x09)
        Blue = self.bus.read_word_data(0x44, 0x0D)
        return (Red, Green, Blue)
    
# Class for obstacle dection.
class Obstacle():

    # Setting up interactions with the ROS-system.
    def __init__(self):
        self._cmd_pub = rospy.Publisher('cmd_vel', Twist, queue_size=1)
        self.obstacle()

    # Function for setting up a scan filter array that gets us information from the lidar.  
    def get_scan(self):
        scan = rospy.wait_for_message('scan', LaserScan)
        scan_filter = []
        scan_filter = list(scan.ranges[0:359])
        # Sorts out all invalid, NaN and zeros from our scan_filter       
        for i in range(len(scan_filter)):
            if scan_filter[i] == float('Inf'):
                scan_filter[i] = 20.0
            if math.isnan(scan_filter[i]):
                scan_filter[i] = 20.0
            elif scan_filter[i] == 0:
                scan_filter[i] = 20.0
        
        # Makes different cone arrays and gets the minimum value from each cone
        Left_front_cone = scan_filter[0:15]
        Right_front_cone = scan_filter[344:359]
        Front_cone = Left_front_cone + Right_front_cone
        Front_cone = min(Front_cone)

        Backing_cone = min(scan_filter[170:190])

        Front_Left_cone = min(scan_filter[16:30])
        Front_Right_cone = min(scan_filter[329:344])

        Left_cone = min(scan_filter[30:70])
        Right_cone= min(scan_filter[290:330])

        return Front_cone, Backing_cone, Front_Left_cone, Front_Right_cone, Left_cone, Right_cone

    def obstacle(self):

        # Initial stats for the program
        twist = Twist()
        turtlebot_moving = True
        Victims_found = 0
        Collision_counter = 0

        # Speed stats
        Accumulated_speed = 0
        Speed_updates = 0

        # Runtime settings
        Run_time = 60 * 2
        End_run = time.time() + Run_time
    
        # ALGORITMS FOR TURTLEBOT MOVEMENTS
        # Turtlebot is moving forward
        def Forward (speed):
            twist.linear.x = speed
            twist.angular.z = 0.0
            self._cmd_pub.publish(twist)
            rospy.loginfo('Moving forward! %f', Front_cone)

        # Turning turtlebot to the right
        def Turn_right (speed,turn):   
            twist.linear.x = speed
            twist.angular.z = -turn
            self._cmd_pub.publish(twist)
            rospy.loginfo('Turning to right! %f', Front_Right_cone)

        # Turning turtlebot to the left
        def Turn_left (speed, turn):
            twist.linear.x = speed
            twist.angular.z = turn
            self._cmd_pub.publish(twist)
            rospy.loginfo('Turning to left! %f', Front_Left_cone)

        # Turtlebot is backing up
        def Backing (speed):   
            twist.linear.x = speed
            twist.angular.z = 0.0
            self._cmd_pub.publish(twist)
            rospy.loginfo('Backing! %f', Backing_cone)

        # Turning around in case of encirclement
        def Turning_around (turn):
            twist.linear.x = 0.0
            twist.angular.z = turn
            self._cmd_pub.publish(twist)
            rospy.loginfo('Turning around!')  

        # Control loop for the program
        while not rospy.is_shutdown() and time.time() < End_run:
            Front_cone, Backing_cone, Front_Left_cone, Front_Right_cone, Left_cone, Right_cone = self.get_scan()
            
            # If turtlebot is moving
            if turtlebot_moving:

                # If there is a wall 
                if Front_cone < COLLISION_DISTANCE:
                    # Backing up turtlebot for one second
                    Backing(-0.5 * LINEAR_VEL)
                    # Stop the turtlebot
                    turtlebot_moving = False  
                    rospy.loginfo('---1---') 

                # RIGHT SOFT TURN
                elif Front_cone < TURNING_DISTANCE and Front_cone > COLLISION_DISTANCE:
                    # If there is more space to the right than to the left, turtlebot will turn right.
                    if Front_Left_cone < Front_Right_cone:
                        # Checking Left and right cones to optimize the turn
                        if Left_cone < Right_cone:
                            Turn_right(LINEAR_VEL, 1) 
                            rospy.loginfo('---2---') 
                            # If there is need for at sharp turn to the right
                            if Front_cone < TURNING_DISTANCE / 1.3:
                                Turn_right(0.2 * LINEAR_VEL, 1)
                                rospy.loginfo('---3---')
                        
                        # If Leftcone > Rightcone we try to turn anyways
                        Turn_right(LINEAR_VEL, 1) 
                        rospy.loginfo('---4---') 
                        # If there is need for at sharp turn to the right
                        if Front_cone < TURNING_DISTANCE / 1.3:
                            Turn_right(0.2 * LINEAR_VEL, 1)
                            rospy.loginfo('---5---')

                    # LEFT SOFT TURN
                    elif Front_Left_cone > Front_Right_cone:
                        # Checking Left and right cones to optimize the turn
                        if Left_cone > Right_cone:
                            Turn_left(LINEAR_VEL, 1)
                            rospy.loginfo('---6---')
                            # If there is need for at sharp turn to the left
                            if Front_cone < TURNING_DISTANCE / 1.3:
                                Turn_left(0.2 * LINEAR_VEL, 1)

                        # If Leftcone < Rightcone we try to turn anyways
                        Turn_left(LINEAR_VEL, 1)
                        rospy.loginfo('---7---')
                        # If there is need for at sharp turn to the left
                        if Front_cone < TURNING_DISTANCE / 1.3:
                            Turn_left(0.2 * LINEAR_VEL, 1)
                        
                # If there is a clear way ahead, turtlebot will move forward.
                else:
                    Forward(LINEAR_VEL)
                    rospy.loginfo('---8---')

                    # If there is consistent faulty scans, turtlebot will back up.
                    if Front_cone > 10.0:
                        while Front_cone < COLLISION_DISTANCE * 1.6:
                            # Turning around
                            Backing(-0.5 * LINEAR_VEL)
                            # Updating the scan values for the next loop
                            Front_cone, _, _, _, _, _ = self.get_scan()
                            rospy.loginfo('---9---')

                        # Start moving forward again
                        turtlebot_moving = True
                        rospy.loginfo('---10---')
                   
            # If turtlebot is NOT moving
            else: 
                # Deciding to turn around itself 
                if Front_cone < COLLISION_DISTANCE:
                    Turn_factor = 1

                    first_scan_value = False
                    turn_start_time = time.time()

                    # Deciding which direction to turn around itself
                    if not first_scan_value:
                        if Front_Left_cone < Front_Right_cone:
                            if Left_cone < Right_cone:
                                Turn_factor = 1
                                rospy.loginfo('---11---')
                        else:
                            if Left_cone > Right_cone:
                                Turn_factor = -1
                                rospy.loginfo('---12---')

                        first_scan_value = True

                    if first_scan_value:
                        turtlebot_moving = False

                        # Turning around itself in given direction untill clear way ahead
                        while Front_cone < COLLISION_DISTANCE * 1.6:
                            Turning_around(Turn_factor)

                            # If the turtlebot is turning around itself for more than 10 seconds, it will back up.
                            if time.time() - turn_start_time > 10:
                                while Backing_cone < COLLISION_DISTANCE * 1.3:
                                    Backing(-0.5 * LINEAR_VEL)

                                    # Updating the scan values for the next loop
                                    _, Backing_cone, _, _, _, _ = self.get_scan()
                                    
                                # Resetting the turn time counter
                                turn_start_time = time.time()

                            # Updating the scan values for the next loop
                            Front_cone, _, _, _, _, _ = self.get_scan()
                            rospy.loginfo('---13---')

                        # Start moving forward again
                        turtlebot_moving = True
                        rospy.loginfo('---14---')
                        

                # All else equal: if there is a clear way ahead we move forward.
                else:
                    Forward(LINEAR_VEL)
                    turtlebot_moving = True
                    rospy.loginfo('---15---')
            
            # Update stats
            #Accumulated_speed += abs(twist.linear.x)
            #Speed_updates += 1
        
            #rospy.on_shutdown(self.Stats)

def main():
    rospy.init_node('turtlebot3_obstacle')
    try:
        obstacle = Obstacle()
    except rospy.ROSInterruptException:
        pass

if __name__ == '__main__':
    main()